name: Development Build

on:
  push:
    branches:
      - feature/*
      - fix/*

jobs:
  build_android:
    name: Build Android (development)
    type: build
    params:
      platform: android
      profile: development